version: 0.8

index_id: quickwit_tantivy

doc_mapping:
  field_mappings:
    - name: url
      type: text
      tokenizer: default
      record: position
      stored: true
    - name: title
      type: text
      tokenizer: default
      record: position
      stored: true
    - name: body
      type: text
      tokenizer: default
      record: position
      stored: true


search_settings:
  default_search_fields: [body]

indexing_settings:
  commit_timeout_secs: 10